import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { studentAPI, authAPI, credentialAPI } from '../services/api';
import { Link, useNavigate } from 'react-router-dom';

const AdminCreateStudent = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [students, setStudents] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStudent, setSelectedStudent] = useState(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [creatingAccount, setCreatingAccount] = useState(false);
  const [generatedPassword, setGeneratedPassword] = useState('');

  const [formData, setFormData] = useState({
    student_id: '',
    student_code: '',
    first_name: '',
    last_name: '',
    username: '',
    email: '',
    password: '',
    confirm_password: '',
    phone: '',
    role: 'student',
    is_student: true
  });

  // Store created credentials
  const [createdCredentials, setCreatedCredentials] = useState([]);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editingCredential, setEditingCredential] = useState(null);
  const [editFormData, setEditFormData] = useState({ username: '', email: '', password: '' });

  useEffect(() => {
    fetchStudents();
    loadCredentials();
  }, []);

  const fetchStudents = async () => {
    try {
      const response = await studentAPI.getAll();
      setStudents(response.data.students || []);
    } catch (err) {
      console.error('Error fetching students:', err);
    }
  };

  const loadCredentials = async () => {
    try {
      const response = await credentialAPI.getAll();
      const credentials = response.data?.credentials || [];
      setCreatedCredentials(credentials);
      saveCredentials(credentials);
    } catch (e) {
      console.error('Could not load credentials from server:', e);
      const saved = localStorage.getItem('studentCredentials');
      if (saved) {
        try {
          setCreatedCredentials(JSON.parse(saved));
        } catch (error) {
          setCreatedCredentials([]);
        }
      }
    }
  };

  const saveCredentials = (credentials) => {
    localStorage.setItem('studentCredentials', JSON.stringify(credentials));
  };

  // Generate student ID based on standard
  const generateStudentId = (standard) => {
    const prefix = `PROG${standard}`;
    const existingStudents = students.filter(s => 
      s.student_id && s.student_id.startsWith(prefix)
    );
    
    let maxNum = 0;
    existingStudents.forEach(s => {
      const numPart = s.student_id.replace(prefix, '');
      const num = parseInt(numPart);
      if (!isNaN(num) && num > maxNum) {
        maxNum = num;
      }
    });
    
    const nextNum = String(maxNum + 1).padStart(3, '0');
    return `${prefix}${nextNum}`;
  };

  // Generate a random password
  const generatePassword = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let password = '';
    for (let i = 0; i < 8; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return password;
  };

  const regeneratePassword = () => {
    const newPassword = generatePassword();
    setGeneratedPassword(newPassword);
    setFormData((prev) => ({
      ...prev,
      password: newPassword,
      confirm_password: newPassword
    }));
  };

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
  };

  const filteredStudents = students.filter(student => 
    !student.user_id &&
    (student.first_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
     student.last_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
     student.student_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
     student.student_id?.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const handleSelectStudent = (student) => {
    const autoGeneratedId = generateStudentId(student.current_standard);
    const autoPassword = generatePassword();
    setGeneratedPassword(autoPassword);
    
    const studentId = student.student_id || autoGeneratedId;
    const studentCode = student.student_code || studentId;
    const firstName = student.first_name || '';
    const lastName = student.last_name || '';
    const baseUsername = `${firstName.toLowerCase()}.${lastName.toLowerCase()}`.replace(/\s+/g, '.');
    const fallbackEmail = `${baseUsername || studentId.toLowerCase()}@school.com`;
    
    setSelectedStudent(student);
    setFormData({
      student_id: studentId,
      student_code: studentCode,
      first_name: firstName,
      last_name: lastName,
      username: baseUsername || studentId,
      email: student.parent_email || fallbackEmail,
      password: autoPassword,
      confirm_password: autoPassword,
      phone: student.phone || '',
      role: 'student',
      is_student: true
    });
    setShowCreateModal(true);
    setError('');
    setSuccess('');
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleCreateAccount = async (e) => {
    e.preventDefault();
    setCreatingAccount(true);
    setError('');
    setSuccess('');

    if (formData.password !== formData.confirm_password) {
      setError('Passwords do not match.');
      setCreatingAccount(false);
      return;
    }

    if (formData.password.length < 6) {
      setError('Password must be at least 6 characters long.');
      setCreatingAccount(false);
      return;
    }

    try {
      const accountData = {
        username: formData.username || formData.email,
        email: formData.email,
        password: formData.password,
        first_name: formData.first_name,
        last_name: formData.last_name,
        role: 'student',
        is_student: true,
        student_id: formData.student_id,
        phone: formData.phone
      };

      const response = await authAPI.createStudentAccount(accountData);
      await loadCredentials();

      setSuccess(`✅ Student account created successfully! Username: ${response.data?.credentials?.username || formData.username} | Password: ${response.data?.credentials?.password || formData.password}`);
      
      await fetchStudents();
      
      setTimeout(() => {
        setShowCreateModal(false);
        setSelectedStudent(null);
        setSuccess('');
        setGeneratedPassword('');
        setFormData({
          student_id: '',
          student_code: '',
          first_name: '',
          last_name: '',
          username: '',
          email: '',
          password: '',
          confirm_password: '',
          phone: '',
          role: 'student',
          is_student: true
        });
      }, 2000);
      
    } catch (err) {
      console.error('Error creating account:', err);
      if (err.response?.status === 404) {
        setError(`Student with ID "${formData.student_id}" not found. Please create the student record first.`);
      } else if (err.response?.status === 409) {
        setError('This student already has an account. Please check the student list.');
      } else {
        setError(err.response?.data?.error || 'Failed to create account. Please try again.');
      }
    } finally {
      setCreatingAccount(false);
    }
  };

  const deleteCredential = (id) => {
    if (window.confirm('Are you sure you want to delete this credential record?')) {
      const updated = createdCredentials.filter(c => c.id !== id);
      setCreatedCredentials(updated);
      saveCredentials(updated);
    }
  };

  const openEditModal = (cred) => {
    setEditingCredential(cred);
    setEditFormData({ username: cred.username || '', email: cred.email || '', password: cred.password || '' });
    setShowEditModal(true);
    setError('');
    setSuccess('');
  };

  const handleEditChange = (e) => {
    const { name, value } = e.target;
    setEditFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSaveEdit = async (e) => {
    e.preventDefault();
    if (!editingCredential) return;
    try {
      // Update via credential API if available
      await credentialAPI.update(editingCredential.id, {
        username: editFormData.username,
        email: editFormData.email,
        password: editFormData.password
      });

      // Update local state and storage
      const updated = createdCredentials.map(c => c.id === editingCredential.id ? ({ ...c, username: editFormData.username, email: editFormData.email, password: editFormData.password }) : c);
      setCreatedCredentials(updated);
      saveCredentials(updated);
      setSuccess('✅ Credential updated');
      setShowEditModal(false);
      setEditingCredential(null);
    } catch (err) {
      console.error('Error updating credential:', err);
      setError(err.response?.data?.error || 'Failed to update credential');
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    alert('Copied to clipboard!');
  };

  const navItems = [
    { title: 'Dashboard', path: '/admin-dashboard', icon: '📊' },
    { title: 'Students', path: '/students', icon: '👨‍🎓' },
    { title: 'Teachers', path: '/teachers', icon: '👨‍🏫' },
    { title: 'Create Student', path: '/admin/create-student', icon: '➕' },
    { title: 'Users', path: '/users', icon: '👥' }
  ];

  return (
    <div className="min-h-screen bg-[#f0f7ff] text-[#1a2a3a] pb-12">
      
      {/* Welcome Banner */}
      <div className="bg-[#003C43] text-white px-6 py-6 shadow-lg">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">
              👋 Welcome back, {user?.first_name || 'Admin'}!
            </h1>
            <p className="text-white/70 text-sm mt-0.5">
              Admin Panel — Create student accounts with login credentials.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="inline-flex items-center space-x-2 bg-white/15 backdrop-blur-md px-3.5 py-1.5 rounded-full text-xs font-medium border border-white/20 text-white/90">
              <span className="w-2 h-2 rounded-full bg-white/70 animate-pulse"></span>
              <span>Academic Year 2026</span>
            </div>
            <button
              onClick={() => {
                logout();
                navigate('/login');
              }}
              className="text-xs font-semibold bg-white/15 hover:bg-white/25 text-white px-4 py-1.5 rounded-full transition-colors border border-white/20"
            >
              🚪 Logout
            </button>
          </div>
        </div>
      </div>

      {/* Navigation Bar */}
      <nav className="bg-[#135D66] text-white border-b border-[#0e4a52] shadow-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="flex items-center justify-between h-14">
            <div className="flex items-center space-x-1 overflow-x-auto">
              {navItems.map((item, index) => (
                <Link
                  key={index}
                  to={item.path}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all duration-200 whitespace-nowrap
                    ${window.location.pathname === item.path 
                      ? 'bg-white/20 text-white' 
                      : 'text-white/70 hover:bg-white/10 hover:text-white'
                    }`}
                >
                  <span>{item.icon}</span>
                  <span>{item.title}</span>
                </Link>
              ))}
            </div>
            <div className="flex items-center space-x-3">
              <span className="text-xs text-white/70 hidden md:inline">
                {user?.first_name || 'Admin'}
              </span>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-8">
        
        {/* Header Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div>
              <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                <span>👨‍🎓</span> Create Student Accounts
              </h2>
              <p className="text-sm text-gray-500 mt-1">
                Assign passwords and generate login credentials for students
              </p>
            </div>
            <div className="flex gap-2 w-full md:w-auto">
              <div className="relative flex-1 md:w-64">
                <input
                  type="text"
                  placeholder="🔍 Search students..."
                  value={searchTerm}
                  onChange={handleSearch}
                  className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition bg-white"
                />
              </div>
              <button
                onClick={fetchStudents}
                className="px-4 py-2 bg-[#135D66] text-white rounded-lg hover:bg-[#0e4a52] transition text-sm whitespace-nowrap"
              >
                Refresh
              </button>
              <Link
                to="/add-student"
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition text-sm whitespace-nowrap"
              >
                + Add Student
              </Link>
            </div>
          </div>
        </div>

        {/* Statistics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-medium uppercase tracking-wider text-gray-500">Total Students</h3>
              <span className="text-lg">👨‍🎓</span>
            </div>
            <p className="text-2xl font-bold text-gray-800 mt-1">{students.length}</p>
          </div>
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-medium uppercase tracking-wider text-gray-500">With Accounts</h3>
              <span className="text-lg">✅</span>
            </div>
            <p className="text-2xl font-bold text-green-600 mt-1">
              {students.filter(s => s.user_id).length}
            </p>
          </div>
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-medium uppercase tracking-wider text-gray-500">Without Accounts</h3>
              <span className="text-lg">⚠️</span>
            </div>
            <p className="text-2xl font-bold text-yellow-600 mt-1">
              {students.filter(s => !s.user_id).length}
            </p>
          </div>
        </div>

        {/* Students List */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          <div className="px-4 py-3 border-b border-gray-200 bg-gray-50">
            <h2 className="text-sm font-semibold text-gray-800 flex items-center gap-2">
              <span>📋</span> Students Without Accounts
              <span className="ml-auto text-xs bg-yellow-100 text-yellow-700 px-2 py-0.5 rounded-full">
                {filteredStudents.length} students
              </span>
            </h2>
          </div>
          
          {filteredStudents.length === 0 ? (
            <div className="text-center py-12 text-gray-400 text-sm bg-white">
              {searchTerm ? 'No students found matching your search.' : 'All students have accounts! 🎉'}
              <div className="mt-4">
                <Link
                  to="/add-student"
                  className="inline-block px-4 py-2 bg-[#135D66] text-white rounded-lg hover:bg-[#0e4a52] transition"
                >
                  + Add New Student
                </Link>
              </div>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-gray-50 text-gray-600 text-xs font-semibold border-b border-gray-200">
                    <th className="px-4 py-2.5">Code</th>
                    <th className="px-4 py-2.5">Student Name</th>
                    <th className="px-4 py-2.5">Standard</th>
                    <th className="px-4 py-2.5">Generated ID</th>
                    <th className="px-4 py-2.5">Parent</th>
                    <th className="px-4 py-2.5">Status</th>
                    <th className="px-4 py-2.5 text-center">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 text-sm">
                  {filteredStudents.map((student) => (
                    <tr key={student.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs bg-gray-100 text-gray-700 px-2 py-0.5 rounded border border-gray-200">
                          {student.student_code || student.student_id}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 font-medium text-gray-800">
                        {student.first_name} {student.last_name}
                      </td>
                      <td className="px-4 py-2.5 text-gray-600">
                        Std {student.current_standard}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded border border-blue-200">
                          {generateStudentId(student.current_standard)}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-gray-500 text-xs">
                        {student.parent_name || 'N/A'}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-yellow-50 text-yellow-700 border border-yellow-200">
                          No Account
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-center">
                        <button
                          onClick={() => handleSelectStudent(student)}
                          className="px-3 py-1.5 bg-[#135D66] text-white rounded-lg hover:bg-[#0e4a52] transition text-xs font-medium whitespace-nowrap"
                        >
                          Create Account
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Created Credentials Table */}
        {createdCredentials.length > 0 && (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            <div className="px-4 py-3 border-b border-gray-200 bg-gray-50 flex items-center justify-between">
              <h2 className="text-sm font-semibold text-gray-800 flex items-center gap-2">
                <span>🔑</span> Created Login Credentials
                <span className="ml-2 text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">
                  {createdCredentials.length} records
                </span>
              </h2>
              <button
                onClick={() => {
                  if (window.confirm('Clear all credential records?')) {
                    setCreatedCredentials([]);
                    saveCredentials([]);
                  }
                }}
                className="text-xs text-red-600 hover:text-red-800 font-medium"
              >
                Clear All
              </button>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-gray-50 text-gray-600 text-xs font-semibold border-b border-gray-200">
                    <th className="px-4 py-2.5">Student ID</th>
                    <th className="px-4 py-2.5">Student Name</th>
                    <th className="px-4 py-2.5">Username</th>
                    <th className="px-4 py-2.5">Email</th>
                    <th className="px-4 py-2.5">Password</th>
                    <th className="px-4 py-2.5">Created</th>
                    <th className="px-4 py-2.5 text-center">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 text-sm">
                  {createdCredentials.map((cred) => (
                    <tr key={cred.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs bg-gray-100 text-gray-700 px-2 py-0.5 rounded border border-gray-200">
                          {cred.student_id}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 font-medium text-gray-800">
                        {cred.student_name}
                      </td>
                      <td className="px-4 py-2.5 text-gray-600">{cred.username}</td>
                      <td className="px-4 py-2.5 text-gray-600 text-xs">{cred.email}</td>
                      <td className="px-4 py-2.5">
                        <div className="flex flex-col gap-1">
                          <div className="text-xs text-gray-600">
                            <span className="font-semibold">User:</span> {cred.username}
                          </div>
                          <div className="flex items-center gap-2">
                            <code className="px-2 py-1 bg-gray-100 rounded text-xs font-mono text-[#135D66]">
                              {cred.password}
                            </code>
                            <button
                              onClick={() => copyToClipboard(cred.login_hint || `Username: ${cred.username}\nPassword: ${cred.password}`)}
                              className="text-gray-400 hover:text-[#135D66] transition"
                              title="Copy username and password"
                            >
                              📋
                            </button>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-2.5 text-gray-500 text-xs">{cred.created_at}</td>
                      <td className="px-4 py-2.5 text-center">
                        <div className="flex items-center justify-center gap-2">
                          <button
                            onClick={() => copyToClipboard(`Username: ${cred.username}\nPassword: ${cred.password}`)}
                            className="px-2 py-1 text-xs bg-blue-50 text-blue-700 rounded hover:bg-blue-100 transition"
                            title="Copy credentials"
                          >
                            📋 Copy
                          </button>
                          <button
                            onClick={() => openEditModal(cred)}
                            className="px-2 py-1 text-xs bg-green-50 text-green-700 rounded hover:bg-green-100 transition"
                          >
                            ✏️ Edit
                          </button>
                          <button
                            onClick={() => deleteCredential(cred.id)}
                            className="px-2 py-1 text-xs bg-red-50 text-red-700 rounded hover:bg-red-100 transition"
                          >
                            🗑️
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Info Card */}
        <div className="bg-gradient-to-r from-[#003C43] to-[#135D66] rounded-lg shadow-sm p-6 text-white">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div>
              <h3 className="text-lg font-bold flex items-center gap-2">
                <span>💡</span> Quick Tips
              </h3>
              <ul className="text-white/70 text-sm mt-2 space-y-1">
                <li>• Student IDs are auto-generated based on their standard</li>
                <li>• Password is auto-generated but you can change it</li>
                <li>• All created credentials are stored in the table below</li>
                <li>• Students can login using their Student ID or Username</li>
                <li>• Click 📋 to copy individual passwords</li>
              </ul>
            </div>
            <div className="bg-white/10 rounded-lg p-4 text-center min-w-[150px]">
              <p className="text-2xl font-bold">{filteredStudents.length}</p>
              <p className="text-xs text-white/70">Pending Accounts</p>
            </div>
          </div>
        </div>

      </div>

      {/* Create Account Modal */}
      {showCreateModal && selectedStudent && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-white rounded-lg shadow-xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-[#135D66] text-white px-6 py-4 rounded-t-lg flex items-center justify-between">
              <h2 className="text-xl font-bold flex items-center gap-2">
                <span>➕</span> Create Student Account
              </h2>
              <button
                onClick={() => {
                  setShowCreateModal(false);
                  setSelectedStudent(null);
                  setError('');
                  setSuccess('');
                }}
                className="text-white/70 hover:text-white transition-colors text-2xl"
              >
                ×
              </button>
            </div>
            
            <form onSubmit={handleCreateAccount} className="p-6">
              {error && (
                <div className="bg-red-50 border-l-4 border-red-500 p-3 mb-4 rounded">
                  <p className="text-red-700 text-sm">{error}</p>
                </div>
              )}
              
              {success && (
                <div className="bg-green-50 border-l-4 border-green-500 p-3 mb-4 rounded">
                  <p className="text-green-700 text-sm">{success}</p>
                </div>
              )}

              <div className="bg-gray-50 p-3 rounded-lg border border-gray-200 mb-4">
                <p className="text-sm font-medium text-gray-800">
                  Creating account for: <span className="text-[#135D66]">{selectedStudent.first_name} {selectedStudent.last_name}</span>
                </p>
                <p className="text-xs text-gray-500 mt-0.5">
                  Standard: {selectedStudent.current_standard} | Student Code: {selectedStudent.student_code || selectedStudent.student_id}
                </p>
                <p className="text-xs text-[#135D66] mt-0.5 font-medium">
                  Generated ID: {formData.student_id}
                </p>
              </div>

              <div className="grid grid-cols-1 gap-3">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Student ID <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="student_id"
                    value={formData.student_id}
                    onChange={handleChange}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg bg-gray-50 font-mono text-[#135D66]"
                    required
                    disabled
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Username <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="username"
                    value={formData.username}
                    onChange={handleChange}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition"
                    required
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Email <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition"
                    required
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Phone Number
                  </label>
                  <input
                    type="text"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Password <span className="text-red-500">*</span>
                  </label>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      name="password"
                      value={formData.password}
                      onChange={handleChange}
                      className="flex-1 px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition font-mono"
                      required
                    />
                    <button
                      type="button"
                      onClick={regeneratePassword}
                      className="px-3 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition text-sm whitespace-nowrap"
                    >
                      🔄 Generate
                    </button>
                  </div>
                  <p className="text-xs text-gray-500 mt-1">Auto-generated or type your own password</p>
                </div>

                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Confirm Password <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="password"
                    name="confirm_password"
                    value={formData.confirm_password}
                    onChange={handleChange}
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#135D66] focus:border-[#135D66] transition"
                    required
                  />
                </div>
              </div>

              <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
                <p className="text-xs text-blue-700">
                  <span className="font-semibold">📌 Note:</span> The student can login using:
                </p>
                <ul className="text-xs text-blue-700 mt-1 list-disc list-inside">
                  <li>Student ID: <span className="font-mono">{formData.student_id}</span></li>
                  <li>Username: <span className="font-mono">{formData.username}</span></li>
                  <li>Email: <span className="font-mono">{formData.email}</span></li>
                </ul>
                <p className="text-xs text-blue-700 mt-1">
                  Password: <span className="font-mono">{formData.password}</span>
                </p>
              </div>

              <div className="flex flex-col sm:flex-row justify-end gap-3 mt-6 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={() => {
                    setShowCreateModal(false);
                    setSelectedStudent(null);
                    setError('');
                    setSuccess('');
                  }}
                  className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition font-medium text-sm"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={creatingAccount}
                  className="px-4 py-2 bg-[#135D66] text-white rounded-lg hover:bg-[#0e4a52] transition disabled:opacity-50 font-medium text-sm flex items-center justify-center gap-2"
                >
                  {creatingAccount ? (
                    <>
                      <span className="animate-spin">⏳</span> Creating...
                    </>
                  ) : (
                    '✅ Create Account'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Credential Modal */}
      {showEditModal && editingCredential && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-[#135D66] text-white px-6 py-4 rounded-t-lg flex items-center justify-between">
              <h2 className="text-xl font-bold flex items-center gap-2">
                <span>✏️</span> Edit Credential
              </h2>
              <button
                onClick={() => {
                  setShowEditModal(false);
                  setEditingCredential(null);
                  setError('');
                  setSuccess('');
                }}
                className="text-white/70 hover:text-white transition-colors text-2xl"
              >
                ×
              </button>
            </div>

            <form onSubmit={handleSaveEdit} className="p-6">
              {error && (
                <div className="bg-red-50 border-l-4 border-red-500 p-3 mb-4 rounded">
                  <p className="text-red-700 text-sm">{error}</p>
                </div>
              )}
              {success && (
                <div className="bg-green-50 border-l-4 border-green-500 p-3 mb-4 rounded">
                  <p className="text-green-700 text-sm">{success}</p>
                </div>
              )}

              <div className="grid grid-cols-1 gap-3">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Username</label>
                  <input type="text" name="username" value={editFormData.username} onChange={handleEditChange} className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg" required />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Email</label>
                  <input type="email" name="email" value={editFormData.email} onChange={handleEditChange} className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg" required />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Password</label>
                  <input type="text" name="password" value={editFormData.password} onChange={handleEditChange} className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg font-mono" required />
                </div>
              </div>

              <div className="flex justify-end gap-3 mt-6">
                <button type="button" onClick={() => { setShowEditModal(false); setEditingCredential(null); }} className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50">Cancel</button>
                <button type="submit" className="px-4 py-2 bg-[#135D66] text-white rounded-lg hover:bg-[#0e4a52]">Save</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminCreateStudent;